services:
  phpadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '9010:80'
    environment:
      - PMA_ARBITRARY=1

  apache:
    build: .
    ports:
      - '8888:80'
    volumes:
      - ./website:/var/www/html/
    depends_on:
      - db
 
  db:
    image: mysql:5.7.40
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: logindb
    ports:
      - '3307:3306'
    volumes:
      - ./db:/var/lib/mysql/
      
